- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: Perform a dist-upgrade with additional arguments
    community.general.zypper:
      name: '*'
      state: dist-upgrade
      allow_vendor_change: true
      extra_args: '--allow-arch-change'
      update_cache: true
