- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: Zypper ref and dup
    community.general.zypper:
      name: '*'
      state: dist-upgrade
      allow_vendor_change: true
      update_cache: true

  - name: Install Solarr (logitech wireless keyboards and mice)
    community.general.zypper:
      name: solaar
      state: present
